// Code generated by MockGen. DO NOT EDIT.
// Source: row.go

// Package processor is a generated GoMock package.
package processor

import (
	reflect "reflect"
	entity "test_quantcast/internal/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// GetFileRow mocks base method.
func (m *MockParser) GetFileRow(input []string) (entity.FileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileRow", input)
	ret0, _ := ret[0].(entity.FileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileRow indicates an expected call of GetFileRow.
func (mr *MockParserMockRecorder) GetFileRow(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileRow", reflect.TypeOf((*MockParser)(nil).GetFileRow), input)
}
